# Generated by Django 3.1.3 on 2023-02-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anwer',
            new_name='Answer',
        ),
    ]
